/**:
  ros__parameters:
    left_ip: HM-TD2B28T-3-T120250109AACHEA3538378.local
    right_ip: HM-TD2B28T-3-T120250408AACHEA4127072.local
    username: admin
    password: ubuntu_define  #后面放到.env里，放置被泄露
    enbale_pub_picture: true
    fire_info_timer_period_ms: 200
    enable_color: true      # 新增：启用彩色图像发布
    enable_ir: true         # 新增：启用红外图像发布

        # 相机标定参数
    camera_distance: 0.294     # 相机间距（米）
    principal_point_x: 0.5      # 主点x（比例，0.5表示图像中心）
    principal_point_y: 0.5      # 主点y（比例）
    
    # TF frame配置
    left_camera_frame: "left_hk_camera_optical_frame"
    right_camera_frame: "right_hk_camera_optical_frame"
    stereo_camera_frame: "stereo_ir_camera"     # 双相机系统frame
    world_frame: "base_link"

    fire_frame_id: "fire_position"   # 火焰位置的frame名称
    publish_fire_tf: true            # 是否发布火焰位置TF

    # 滤波参数
    kalman_process_noise: 0.01      # 增大过程噪声
    kalman_measurement_noise: 0.1   # 增大测量噪声
    moving_average_window: 5        # 减小窗口大小
    outlier_threshold: 1.0          # 增大异常值阈值到1米

    rtsp_port: 554
    color_stream_path: "/Streaming/Channels/1"  # 彩色码流
    ir_stream_path: "/Streaming/Channels/2"     # 红外码流
    enable_color_stream: true
    enable_ir_stream: false
    frame_rate: 25.0
    timeout_ms: 5000

    jpeg_quality: 80        # JPEG质量 (1-100, 数值越高质量越好但文件越大)
    png_compression: 3      # PNG压缩级别 (0-9, 数值越高压缩越强但速度越慢)
