spatio_temporal_voxel_layer:
        plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
        enabled: true
        voxel_decay: 15.
        decay_model: 0
        voxel_size: 0.05
        track_unknown_space: true
        unknown_threshold: 15
        mark_threshold: 0
        update_footprint_enabled: true
        combination_method: 1
        origin_z: 0.0
        publish_voxel_map: true
        transform_tolerance: 0.3
        mapping_mode: false
        map_save_duration: 60.0
        observation_sources: depth_cam
        depth_cam:
          data_type: PointCloud2
          topic: /depth_cam/depth/points
          marking: true
          clearing: true
          obstacle_range: 2.0
          min_obstacle_height: 0.1524
          max_obstacle_height: 0.8
          expected_update_rate: 0.0
          observation_persistence: 0.0
          inf_is_valid: false
          filter: "voxel"
          voxel_min_points: 0
          clear_after_reading: true
          max_z: 2.0
          min_z: 0.2
          vertical_fov_angle: 1.047
          horizontal_fov_angle: 1.221
          decay_acceleration: 15.0
          model_type: 0