voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 40
        # min_obstacle_height: 0.05
        max_obstacle_height: 2.0
        mark_threshold: 2  # dabai_dcw 对应纸盒，2无法识别，0导致太多障碍，无法执行
        # unknown_threshold: 15 
        observation_sources: depth_cam
        depth_cam:
          topic: /depth_cam/depth/points
          data_type: "PointCloud2"
          raytrace_min_range: 0.2
          raytrace_max_range: 8.0
          obstacle_min_range: 0.2
          obstacle_max_range: 7.
          min_obstacle_height: 0.05
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          inf_is_valid: false